name: QMS Message Update

on:
  workflow_dispatch:
    inputs:
      targetVersion:
        type: string
        description: 'The version of the QMS message to update'
        required: true
      message:
        type: string
        description: 'The message to be sent to the user'
        required: true
      expirationDate:
        type: string
        description: 'The expiration date of the message (format: YYYY-MM-DD)'
        required: true

permissions:
  contents: write

jobs:
  update_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update QMS message
        shell: bash
        run: |
          SECRET_TARGET_VERSION=$(jq -r '.inputs.targetVersion' $GITHUB_EVENT_PATH)
          echo "::add-mask::$SECRET_TARGET_VERSION"
          
          SECRET_MESSAGE=$(jq -r '.inputs.message' $GITHUB_EVENT_PATH)
          echo "::add-mask::$SECRET_MESSAGE"
          
          SECRET_EXPIRATION_DATE=$(jq -r '.inputs.expirationDate' $GITHUB_EVENT_PATH)
          echo "::add-mask::$SECRET_EXPIRATION_DATE"

          echo "Updating QMS message..."
          jq --indent 4 --arg targetVersion "$SECRET_TARGET_VERSION" '.targetVersion = $targetVersion' message.json > tmp.json && mv tmp.json message.json
          jq --indent 4 --arg message "$SECRET_MESSAGE" '.message = $message' message.json > tmp.json && mv tmp.json message.json
          jq --indent 4 --arg expirationDate "$SECRET_EXPIRATION_DATE" '.expirationDate = $expirationDate' message.json > tmp.json && mv tmp.json message.json

      - name: Encrypt QMS Message
        shell: bash
        run: |
          echo "Encrypting QMS message..."
          openssl enc -aes-256-cbc -md md5 -salt -in message.json -out message.enc -pass pass:${{ secrets.PASSWORD }}

      - name: Commit and push changes
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add message.enc
          git commit -m "Update JSON file with new inputs"
          git push