name: QMS Message Update

on:
  workflow_dispatch:
    inputs:
      targetVersion:
        type: string
        description: 'The version of the QMS message to update'
        required: true
      message:
        type: string
        description: 'The message to be sent to the user'
        required: true
      expirationDate:
        type: string
        description: 'The expiration date of the message (format: YYYY-MM-DD)'
        required: true

permissions:
  contents: write

jobs:
  update_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask inputs
        run: |
          INPUT_TARGET_VERSION=$(jq -r '.inputs.targetVersion' <<< "${{ inputs.targetVersion }}")
          INPUT_MESSAGE=$(jq -r '.inputs.message' <<< "${{ inputs.message }}")
          INPUT_EXPIRATION_DATE=$(jq -r '.inputs.expirationDate' <<< "${{ inputs.expirationDate }}")
          echo ::add-mask::$INPUT_TARGET_VERSION
          echo ::add-mask::$INPUT_MESSAGE
          echo ::add-mask::$INPUT_EXPIRATION_DATE

      - name: Update QMS message
        shell: bash
        run: |
          echo "Updating QMS message..."
          cat <<< "$(jq --indent 4 '.targetVersion = "$INPUT_TARGET_VERSION"' message.json)" > message.json
          cat <<< "$(jq --indent 4 '.message = "$INPUT_MESSAGE"' message.json)" > message.json
          cat <<< "$(jq --indent 4 '.expirationDate = "$INPUT_EXPIRATION_DATE"' message.json)" > message.json

      - name: Encrypt QMS Message
        shell: bash
        run: |
          echo "Encrypting QMS message..."
          openssl aes-256-cbc -in message.json -out message.enc -pass pass:${{ secrets.PASSWORD }}

      - name: Commit and push changes
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add message.enc
          git commit -m "Update JSON file with new inputs"
          git push